#!/bin/sh

###############################################################################
## Autostart script.
## This script is called from i3 and triggers some settings and spawns some
## applications.
##
## Sebastian Ruml, <sebastian@sebastianruml.name>, 2017
##
## Credits: The main part of the script is taken from https://github.com/lzap/doti3
###############################################################################

# Wait for program coming up
wait_for_program () {
  n=0
  while true
  do
    # PID of last background command
    if xdotool search --onlyvisible --pid $! 2>/dev/null; then
      break
    else
      if [ $n -eq 90 ]; then
        notify-send -u critical "Error during start"
        break
      else
        n=`expr $n + 1`
        sleep 0.5
      fi
    fi
  done
}


#####
## Monitor configuration
#####

## Determine connected monitors
#VGA_YES=0
#DP_YES=0
#ANY_YES=0
#xrandr | grep -Eq "DP[12345] connected" && DP_YES=1 && ANY_YES=1
#xrandr | grep -Eq "VGA[12345] connected" && VGA_YES=1 && ANY_YES=1
#DP=$(xrandr | grep -E "DP[12345] connected" | grep -oE "DP[12345]")
#VGA=$(xrandr | grep -E "VGA[12345] connected" | grep -oE "VGA[12345]")

# Configuring monitors
xrandr --output DVI-I-1 --mode 1920x1200 --right-of DVI-D-0 --output DVI-D-0 --mode 1920x1200

## Merge Xresources
xrdb -merge ~/.Xresources &

## Terminal daemon
#urxvt256cd -q -f -o &
TERMINAL=xfce4-terminal

## Set startup volume (use pactl info to determine sink name)
#pactl set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo '60%' &

## Disable beeps
xset -b &

## Keybord layout setting
setxkbmap -layout de

## Gamma correction through the X server
#xgamma -gamma 1.1 &


####
## Configure input devices
####

# set keyboard repeat speed
xset r rate 250 80 2>&1

# set mouse acceleration
xset m 4/1 4 2>&1


####
## Apps and workspaces setup
####

## OSD
LC_ALL=C feh --bg-fill /usr/share/backgrounds/girl_face_explosion.jpg &
LC_ALL=C dunst &
LC_ALL=C compton &
LC_ALL=C conky -c ~/.conky/conkyrc_right &
LC_ALL=C conky -c ~/.conky/conkyrc_left &


## Workspaces 1-4
for w in 1 2 3 4; do
  	ws = w$w

  	i3-msg workspace $ws

  	$TERMINAL &
  	wait_for_program

	i3-msg layout tabbed

	$TERMINAL &
	wait_for_program

	i3-msg focus left
done


## Refresh
xrefresh &

## Start taskbar utils
LC_ALL=C nm-applet &>/dev/null &
LC_ALL=C clipit &>/dev/null &
LC_ALL=C dropbox start &>/dev/null &

## Update dmenu cache
dmenu_path >/dev/null&

## Good work :-)
exit 0
