#!/usr/bin/env bash

set -euo pipefail

##? Setups the environment
#?? 1.0.0
##?
##? Usage:
##?    install

echo "🚀 Welcome to the hypebeast/dotfiles installer!"
echo "-----------------------------------------------"
echo

export DOTFILES="$HOME/.dotfiles"

echo "👉  Cloning into: '$DOTFILES'"
echo "❗ If no developers are found, MacOS will request to install it. You need to wait until the installation is complete. After that, you need to restart this script."
echo
echo

# To test that git is installed (if not macOS will prompt an installer)
git --version

git clone --depth 1 https://github.com/hypebeast/dotfiles.git "$DOTFILES"

cd "$DOTFILES"
./scripts/bootstrap.sh