#!/bin/sh
# Since Sublime is fucking insane and can't handle symlinks for the User
# directory, we'll need to manually copy stuff over.

rm -rf $DOTFILES/sublime2/User
cp -R ~/Library/Application\ Support/Sublime\ Text/Packages/User $DOTFILES/sublime2/User
