#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES/scripts/core/_main.sh"

##? Export all installed packages
#?? 1.0.0
##?
##? Usage:
##?    export

docs::eval "$@"

brew services stop --all
brew bundle dump --file="$HOMEBREW_BUNDLE_FILE_PATH" --force
echo 'Brew apps exported!'

#pip3 freeze >"$DOTFILES/langs/python/requirements.txt"
#echo 'Python apps exported!'

#ls -1 /usr/local/lib/node_modules | grep -v npm >"$DOTFILES/langs/node/global_modules.txt"
#echo 'NPM apps exported!'