#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES/scripts/core/_main.sh"

#? v0.1.0
#? Copyright (C) 2023 Sebastian Ruml <sebastian.ruml@gmail.com>

##? Usage: install [PACKAGE]
##?
##? Installs a package with brew. If no package name is provided, brew search is started.
##?
##? Arguments:
##?   PACKAGE The brew package which should be installed.

docs::eval "$@"

echo "$#"

if [[ $# == 0 ]] || [[ -z "$1" ]]; then
  package=$(brew search | fzf)
else
  package=$(brew search $1 | fzf)
fi

if [[ -z ${package} ]]; then
  echo "You haven't selected any package to install! ༼つ◕_◕༽つ"
  exit 1
fi

brew install ${package}